kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: new-joiner
rules:
  - apiGroups: ["", "apps"] # empty represents access to resources that are having apiVersion as v1 this is also referred as core group
    resources: ["*"] # * means all K8S resources like pods, services, deployments etc
    verbs: ["get", "list", "watch"] # actions that user can perform on the resources.

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: put-specific-user-or-users-into-new-joiner-role
subjects:
  - kind: User
    name: francis-linux-login-name
roleRef:
  kind: ClusterRole
  name: new-joiner
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: new-joiner
  namespace: playground
rules:
  - apiGroups: ["", "apps"] 
    resources: ["*"] 
    verbs: ["*"] 

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: new-joiners-role-binding
  namespace: playground
subjects:
  - kind: User
    name: francis-linux-login-name
roleRef:
  kind: Role
  name: new-joiner
  apiGroup: rbac.authorization.k8s.io