apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  # This defines which pods are going to be represented by this service
  # The service becomes a network endpoint for either other services 
  # or may be external users to connect to (eg: browser)
  selector:
    app: webapp
    release: "0-5"

  ports:
    - name: http
      # This port is the container port 
      port: 80
      # This is an external port
      nodePort: 30080

  type: NodePort
